### ISSUE TITLE
Installation Instructions

### ISSUE THREAD

**Issue by dasguptar** [kmul00/torch-vol#1]
It would be nice to have some installation instructions with the README. 
As far as I can see, simply copying these files to the appropriate 'nn' folder and then doing a `luarocks install` with the appropriate rocks file in the nn folder would be sufficient.
Maybe adding those instructions (or any other installation instructions) to the README would be useful.

**Comment by kmul00** [comment]
Thank you @dasguptar  for pointing it out. I will update regarding how to use these modules within the existing `nn` or `cunn` package, soon.

**Comment by kmul00** [comment]
Updated !
