### ISSUE TITLE
VolumetricUpSamplingNearest: input.nn is a nil value

### ISSUE THREAD

**Issue by yi-ji** [kmul00/torch-vol#2]
Hi,

First I want to say your work is awesome, would definitely help me. But about the installation, I think there should be some update, because I actually installed your module in extra/nnx and extra/cunnx, seems newest version of torch has made some changes in directory structures.

However I got a problem when I use VolumetricUpSamplingNearest in my module.
This is my model:

```
local pooling = nn.VolumetricMaxPooling(3,3,3)
local pooling2 = nn.VolumetricMaxPooling(2,2,2)

encoder = nn.Sequential()
encoder:add(nn.VolumetricConvolution(1,10,7,7,7))
encoder:add(nn.Sigmoid())
encoder:add(pooling)
encoder:add(nn.VolumetricConvolution(10,20,5,5,5))
encoder:add(nn.Sigmoid())
encoder:add(pooling2)
encoder:add(nn.VolumetricConvolution(20,30,3,3,3))
encoder:add(nn.Sigmoid())

decoder = nn.Sequential()
decoder:add(nn.VolumetricFullConvolution(30,20,3,3,3))
encoder:add(nn.Sigmoid())
decoder:add(nn.VolumetricUpSamplingNearest(2,2))
decoder:add(nn.VolumetricFullConvolution(20,10,5,5,5))
encoder:add(nn.Sigmoid())
decoder:add(nn.VolumetricUpSamplingNearest(3,3))
decoder:add(nn.VolumetricFullConvolution(10,1,7,7,7))

module = unsup.SparseAutoEncoder(encoder, decoder, params.beta, params.lambda)
```

The input is a 3D Tensor (100x100x100). I think I make it right above. But when training it gives this:

```
/usr/share/lua/5.1/nn/VolumetricUpSamplingNearest.lua:55: attempt to index field 'nn' (a nil value)
stack traceback:

    /usr/share/lua/5.1/nn/VolumetricUpSamplingNearest.lua:55: in function </usr/share/lua/5.1/nn/VolumetricUpSamplingNearest.lua:33>

    [C]: in function 'xpcall'

    /usr/share/lua/5.1/nn/Container.lua:65: in function 'rethrowErrors'

    /usr/share/lua/5.1/nn/Sequential.lua:44: in function 'updateOutput'

    /usr/share/lua/5.1/unsup/SparseAutoEncoder.lua:36: in function 'updateOutput'

    train-cbct-whole.lua:212: in function 'opfunc'

    /usr/share/lua/5.1/optim/adagrad.lua:31: in function 'adagrad'

    train-cbct-whole.lua:233: in main chunk
```

I am not quite sure what is input.nn, so I wll appreciate your kindly help! Thank you very much.

**Comment by kmul00** [comment]
Hi,

Thank you for your kind words.

And I would like to apologise since the repo is not at all up to date. Actually Torch has undergone some changes in it's backend since I last updated this repo. All it's function calls are made independent of `Lua` now and moved to `THNN` (and `THCUNN` for `CUDA`).

So unfortunately, the installation procedure mentioned in the `README` won't work any longer. 

I will update the `README`. Also, most of the modules are already merged into the main `nn` repo, so have a look there. If there's something which still isn't there, but you need it, let me know. I will provide you with the corresponding code that adheres to the current `nn` directory structure.

**Comment by yi-ji** [comment]
Thank you for your reply!
I think I would just need the VolumetricUpSamplingNearest module, and I think I have installed it correctly, but it will still be great to have some of your corresponding code that adheres to help me debug current problem.

**Comment by kmul00** [comment]
Since you say that you have installed it in the `nnx` directory, it shouldn't have any problem working. Did you do `require 'nnx'` in your code ?

**Comment by yi-ji** [comment]
Yes, but still. And I have also tried CPU and GPU, both failed. Maybe in fact I didn't finish the installation completely? Hoping your new updated README could help...

**Comment by kmul00** [comment]
Hi,

I just tried, I followed all the instruction as given in `install.md`, just instead of `nn` I used `nnx`, and it worked perfectly.

I would suggest that you remove your build directory, and try to `make` in correctly once again. Also try updating your `nn` and `torch` using `luarocks install` and see if it helps.

**Comment by yi-ji** [comment]
Hi,
I am not sure whether I installed it all good, I can't tell if it was something wrong in my torch model. So could you please show me your test code of VolumetricUpSamplingNearest to help me check my installation?

**Comment by kmul00** [comment]
``` lua
th> require 'nnx';
th> input = torch.Tensor(1, 10, 10, 10)
th> model = nn.Sequential()
th> model:add(nn.VolumetricUpSamplingNearest(2, 2))
nn.Sequential {
  [input -> (1) -> output]
  (1): nn.VolumetricUpSamplingNearest
}
th> out = model:forward(input)

th> input:size()
  1
 10
 10
 10
[torch.LongStorage of size 4]

th> out:size()
  1
 20
 20
 20
[torch.LongStorage of size 4]
```

**Comment by yi-ji** [comment]
Oh... it's my fault, only if I required 'nnx' and run in CPU mode it will work.
But when running in GPU mode, if I require 'cunnx', it gives errors as below:

```
/usr/bin/luajit: /usr/share/lua/5.1/trepl/init.lua:384: 
/usr/share/lua/5.1/trepl/init.lua:384: /usr/share/lua/5.1/luarocks/loader.lua:117: 
error loading module 'libcunnx' from file '/usr/lib/lua/5.1/libcunnx.so':
    /usr/lib/lua/5.1/libcunnx.so: undefined symbol: _Z37cunn_VolumetricUpSamplingNearest_initP9lua_State
stack traceback:
    [C]: in function 'error'
    /usr/share/lua/5.1/trepl/init.lua:384: in function 'require'

```

So I am wondering, have you tried test it in GPU mode using cunn?
Thank you for your patience so much!!

**Comment by kmul00** [comment]
Sure, no problem. 

Actually I have tested only the `CPU` mode. Let me check the `GPU` as well, and get back to you.

**Comment by kmul00** [comment]
Hi,

Just follow whatever instruction is given in the `INSTALL.md` file, but before that you just need to do one additional thing.

You need to change all the occurrences of `cunn` in the `VolumetricUpSamplingNearest.cu` file to `cunnx`.

That is, e.g. 

``` cpp
void cunn_VolumetricUpSamplingNearest_init(lua_State *L)
```

should become,

``` cpp
void cunnx_VolumetricUpSamplingNearest_init(lua_State *L)
```

And likewise for every occurrence of `cunn`.

And once you have made all the above changes, remove the `build` directory and `make` afresh. That will resolve the problem.

**Comment by yi-ji** [comment]
Hi friend,

It's all clear now! Thank you for your help :) Very cool.
