### ISSUE TITLE
VolumetricMaxUnpooling module installation

### ISSUE THREAD

**Issue by yi-ji** [kmul00/torch-vol#3]
Hi friend,

Sorry to bother you again. I just noticed that the `VolumetricMaxUnpooling.cu` module in torch is contributed by you as well and I want to install it in my cunn. However, I can't do it by `luarocks install cunn` because it causes too many errors and I also want to keep my current cunn version. 

So I am wondering is there another way to install it just like before? Have you tried this? Thanks!!

——————
I have tried to install by copying `VolumetricMaxUnpooling.cu` into `/home/ubuntu/torch/extra/cunn/lib/THCUNN` and then `luarocks make cunn`, but when training models it got 

```
not found: THNN_CudaVolumetricMaxUnpooling_updateOutput
/usr/share/lua/5.1/nn/THNN.lua:107: /usr/lib/lua/5.1/libTHCUNN.so: undefined symbol: THNN_CudaVolumetricMaxUnpooling_updateOutput   
not found: THNN_CudaVolumetricMaxUnpooling_updateGradInput
/usr/share/lua/5.1/nn/THNN.lua:107: /usr/lib/lua/5.1/libTHCUNN.so: undefined symbol: THNN_CudaVolumetricMaxUnpooling_updateGradInput
```

I tried to fixed it by adding the missing function definition into `/usr/share/lua/5.1/cunn/THCUNN_h.lua` but it still doesn't work.

**Comment by yi-ji** [comment]
Oh I think I just fixed this... I'm sorry

Just need to 
1. Copy `VolumetricMaxUnpooling.cu` into `torch/extra/cunn/lib/THCUNN/`
2. Find the function definition of `THNN_CudaVolumetricMaxUnpooling_updateOutput` and `THNN_CudaVolumetricMaxUnpooling_updateGradInput` in the newest `THCUNN.h` and added to yours
3. rebuild cunn

Hope I didn't bother you too much...

**Comment by kmul00** [comment]
Hi,

It's okay, no worries at all . :)
